package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import tarce.model.greendaoBean.ContactsBean;
import tarce.model.greendaoBean.LoginResponseBean;
import tarce.model.greendaoBean.MenuListBean;
import tarce.model.greendaoBean.SupplierBean;
import tarce.model.greendaoBean.UserLogin;

import greendao.ContactsBeanDao;
import greendao.LoginResponseBeanDao;
import greendao.MenuListBeanDao;
import greendao.SupplierBeanDao;
import greendao.UserLoginDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactsBeanDaoConfig;
    private final DaoConfig loginResponseBeanDaoConfig;
    private final DaoConfig menuListBeanDaoConfig;
    private final DaoConfig supplierBeanDaoConfig;
    private final DaoConfig userLoginDaoConfig;

    private final ContactsBeanDao contactsBeanDao;
    private final LoginResponseBeanDao loginResponseBeanDao;
    private final MenuListBeanDao menuListBeanDao;
    private final SupplierBeanDao supplierBeanDao;
    private final UserLoginDao userLoginDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactsBeanDaoConfig = daoConfigMap.get(ContactsBeanDao.class).clone();
        contactsBeanDaoConfig.initIdentityScope(type);

        loginResponseBeanDaoConfig = daoConfigMap.get(LoginResponseBeanDao.class).clone();
        loginResponseBeanDaoConfig.initIdentityScope(type);

        menuListBeanDaoConfig = daoConfigMap.get(MenuListBeanDao.class).clone();
        menuListBeanDaoConfig.initIdentityScope(type);

        supplierBeanDaoConfig = daoConfigMap.get(SupplierBeanDao.class).clone();
        supplierBeanDaoConfig.initIdentityScope(type);

        userLoginDaoConfig = daoConfigMap.get(UserLoginDao.class).clone();
        userLoginDaoConfig.initIdentityScope(type);

        contactsBeanDao = new ContactsBeanDao(contactsBeanDaoConfig, this);
        loginResponseBeanDao = new LoginResponseBeanDao(loginResponseBeanDaoConfig, this);
        menuListBeanDao = new MenuListBeanDao(menuListBeanDaoConfig, this);
        supplierBeanDao = new SupplierBeanDao(supplierBeanDaoConfig, this);
        userLoginDao = new UserLoginDao(userLoginDaoConfig, this);

        registerDao(ContactsBean.class, contactsBeanDao);
        registerDao(LoginResponseBean.class, loginResponseBeanDao);
        registerDao(MenuListBean.class, menuListBeanDao);
        registerDao(SupplierBean.class, supplierBeanDao);
        registerDao(UserLogin.class, userLoginDao);
    }
    
    public void clear() {
        contactsBeanDaoConfig.clearIdentityScope();
        loginResponseBeanDaoConfig.clearIdentityScope();
        menuListBeanDaoConfig.clearIdentityScope();
        supplierBeanDaoConfig.clearIdentityScope();
        userLoginDaoConfig.clearIdentityScope();
    }

    public ContactsBeanDao getContactsBeanDao() {
        return contactsBeanDao;
    }

    public LoginResponseBeanDao getLoginResponseBeanDao() {
        return loginResponseBeanDao;
    }

    public MenuListBeanDao getMenuListBeanDao() {
        return menuListBeanDao;
    }

    public SupplierBeanDao getSupplierBeanDao() {
        return supplierBeanDao;
    }

    public UserLoginDao getUserLoginDao() {
        return userLoginDao;
    }

}
